INSERT INTO `items` (`name`, `label`) VALUES
	('firework1','Firework Cylinder Small Red'),
	('firework2','Firework Cylinder Small Green'),
	('firework3','Firework Cylinder Small Blue'),
	('firework4','Firework Cylinder Small Yellow'),
	('firework5','Firework Cylinder Medium Red'),
	('firework6','Firework Cylinder Medium Green'),
	('firework7','Firework Cylinder Medium Blue'),
	('firework8','Firework Cylinder Medium Yellow'),
	('firework9','Firework Box Small Red'),
	('firework10','Firework Box Small Green'),
	('firework11','Firework Box Small Blue'),
	('firework12','Firework Box Small Yellow'),
	('firework13','Firework Box Medium Red'),
	('firework14','Firework Box Medium Green'),
	('firework15','Firework Box Medium Blue'),
	('firework16','Firework Box Medium Yellow'),
	('firework17','Firework Rocket Small'),
	('firework18','Firework Rocket Medium'),
	('firework19','Firework Rocket Big'),
	('firework20','Firework Burst Small Red'),
	('firework21','Firework Burst Small Green'),
	('firework22','Firework Burst Small Blue'),
	('firework23','Firework Burst Small Yellow'),
	('firework24','Firework Burst Medium Red'),
	('firework25','Firework Burst Medium Green'),
	('firework26','Firework Burst Medium Blue'),
	('firework27','Firework Burst Medium Yellow'),
	('firework28','Firework Burst Medium Random'),
	('firework29','Firework Cylinder Medium Random'),
	('firework30','Firework Box Medium Random');